### ISSUE TITLE
Some prompt icons display as question mark boxes

### ISSUE THREAD

**Issue by crismali** [daytonn/baptize#4]
`GBRANCH_ICON` and `BAPTIZE_POWERLINE_THEME` (the `sep` variable) render as question mark boxes by default in the Iterm 3 beta
![screen shot 2016-03-24 at 1 21 46 pm](https://cloud.githubusercontent.com/assets/3209502/14026980/6aef9a28-f1c3-11e5-8184-f5610fca479b.png)

Right now I can turn off the power line, but to fix the branch icon I have to edit the `git_prompt.sh`. 

Is there something I need to turn on in Iterm or something I'm missing?

**Comment by daytonn** [comment]
You need a powerline patched font: https://github.com/powerline/fonts
-- 
Dayton Nolan

On March 24, 2016 at 1:24:20 PM, Michael (notifications@github.com) wrote:

GBRANCH_ICON and BAPTIZE_POWERLINE_THEME (the sep variable) render as question mark boxes by default in the Iterm 3 beta

Right now I can turn off the power line, but to fix the branch icon I have to edit the git_prompt.sh.

Is there something I need to turn on in Iterm or something I'm missing?

**Comment by crismali** [comment]
I've installed the fonts but when I use them in Iterm they still show up as question mark boxes. Plus, I have to leave behind my preferred font.

**Comment by daytonn** [comment]
What's your preferred font? Did you set iTerm to use the patched font?

-- 
Dayton Nolan

On March 25, 2016 at 2:30:59 PM, Michael (notifications@github.com) wrote:

I've installed the fonts but when I use them in Iterm they still show up as question mark boxes. Plus, I have to leave behind my preferred font.

**Comment by daytonn** [comment]
You can patch fonts with this https://github.com/powerline/fontpatcher.
-- 
Dayton Nolan

On March 25, 2016 at 2:32:41 PM, Dayton Nolan (daytonn@gmail.com) wrote:

What's your preferred font? Did you set iTerm to use the patched font?

-- 
Dayton Nolan

On March 25, 2016 at 2:30:59 PM, Michael (notifications@github.com) wrote:

I've installed the fonts but when I use them in Iterm they still show up as question mark boxes. Plus, I have to leave behind my preferred font.

**Comment by daytonn** [comment]
There's also a prepatched Monaco here: https://gist.github.com/baopham/1838072
-- 
Dayton Nolan

On March 25, 2016 at 2:36:33 PM, Dayton Nolan (daytonn@gmail.com) wrote:

You can patch fonts with this https://github.com/powerline/fontpatcher.
-- 
Dayton Nolan

On March 25, 2016 at 2:32:41 PM, Dayton Nolan (daytonn@gmail.com) wrote:

What's your preferred font? Did you set iTerm to use the patched font?

-- 
Dayton Nolan

On March 25, 2016 at 2:30:59 PM, Michael (notifications@github.com) wrote:

I've installed the fonts but when I use them in Iterm they still show up as question mark boxes. Plus, I have to leave behind my preferred font.

**Comment by crismali** [comment]
I set iterm to use the patched Monaco, but it didn't change anything.

**Comment by daytonn** [comment]
Be sure to only use one font, in the new iTerm you can turn off mono space

## fonts, try that

Dayton Nolan

**Comment by crismali** [comment]
Ah, two fonts, that did the trick. Thanks!
